#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

nj=16
stage=1
stop_stage=3
version=large
dl_dir=/home/shahn/Datasets/reazonspeech-v2

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
    # This function is from espnet
    local fname=${BASH_SOURCE[1]##*/}
    echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh"

log "dl_dir: $dl_dir"

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
    log "Stage 0: Download & untar ReazonSpeech data"
    python $dl_dir/download.py --dataset $version --path $dl_dir
    python $dl_dir/untar.py --path $dl_dir
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
    log "Stage 1: Prepare ReazonSpeech manifest"
    mkdir -p data/manifests
    if [ ! -e data/manifests/.reazonspeech.done ]; then
        lhotse prepare reazonspeech -j $nj --num-dev 2000 --num-test 2000 $dl_dir/ReazonSpeech data/manifests
        touch data/manifests/.reazonspeech.done
    fi
fi

vocab_size=500
lang_dir=data/lang_bpe_${vocab_size}_hiragana_filtered
mkdir -p $lang_dir
if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
    log "Stage 2: Filter ReazonSpeech manifests"
    if [ ! -e data/manifests/.reazonspeech-filtered.done ]; then
        python local/filter_reazonspeech.py --data-dir data --transcript-dir $lang_dir
        touch data/manifests/.reazonspeech-filtered.done
    fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
    log "Stage 3: Compute ReazonSpeech fbank"
    if [ ! -e data/manifests/.reazonspeech-validated.done ]; then
        python local/compute_fbank_reazonspeech.py --manifest-dir data/manifests --fbank-dir /home/shahn/Documents/icefall/egs/librispeech/ASR/data/fbank
        python local/validate_manifest.py --manifest data/manifests/reazonspeech_cuts_train.jsonl.gz
        python local/validate_manifest.py --manifest data/manifests/reazonspeech_cuts_dev.jsonl.gz
        python local/validate_manifest.py --manifest data/manifests/reazonspeech_cuts_test.jsonl.gz
        touch data/manifests/.reazonspeech-validated.done
    fi
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
    log "Stage 4: Train bpe for ReazonSpeech"
    if [ ! -f $lang_dir/bpe.model ]; then
        ./local/train_bpe_model.py \
            --lang-dir $lang_dir \
            --vocab-size $vocab_size \
            --transcript $lang_dir/transcript_words.txt
    fi
fi

if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
    log "Stage 5: Show manifest statistics"
    python local/display_manifest_statistics.py --manifest-dir data/manifests > data/manifests/manifest_statistics.txt
    cat data/manifests/manifest_statistics.txt
fi