#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

nj=32
stage=1
stop_stage=6
subset=large
vocab_size=500
dl_dir=/home/shahn/Datasets/reazonspeech-v2
manifests_dir=data/manifests
fbank_dir=/home/shahn/Documents/icefall/egs/librispeech/ASR/data/fbank
lang_dir=data/lang_bpe_${vocab_size}
export CUDA_VISIBLE_DEVICES=0

# Split a subset into multiple splits to avoid OOM during feature extraction.
# Each split will contain `num_per_split` utterances.
num_per_split=10000

split_dir=${fbank_dir}/reazonspeech_${subset}_split_train

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
    # This function is from espnet
    local fname=${BASH_SOURCE[1]##*/}
    echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh"

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
    log "Stage 0: Download & untar ReazonSpeech data"
    log "subset: ${subset}, dl_dir: $dl_dir"
    python $dl_dir/download.py --subset $subset --path $dl_dir
    python $dl_dir/untar.py --path $dl_dir
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
    log "Stage 1: Prepare ReazonSpeech manifests & cuts"
    mkdir -p data/manifests
    python local/prepare_reazonspeech.py -s $subset -m $manifests_dir -r $dl_dir -l $lang_dir
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
    log "Stage 2: Split ${subset}_train into pieces (may take 30 minutes)"
    mkdir -p $split_dir
    if [ ! -f $split_dir/.split_completed ]; then
        lhotse split-lazy \
            ${manifests_dir}/reazonspeech_${subset}_cuts_train_raw.jsonl.gz \
            $split_dir \
            $num_per_split
        touch $split_dir/.split_completed
    fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
    log "Stage 3: Compute fbank for ${subset}_train"
    python local/compute_fbank_reazonspeech_splits.py -s $subset -f $fbank_dir
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
    log "Stage 4: Combine fbank for ${subset}_train (may take 3 hours)"
    if [ ! -f ${fbank_dir}/reazonspeech_${subset}_cuts_train.jsonl.gz ]; then
        pieces=$(find $split_dir -name "reazonspeech_${subset}_cuts_train.*.jsonl.gz")
        output_path=${fbank_dir}/reazonspeech_${subset}_cuts_train.jsonl.gz
        lhotse combine $pieces $output_path
        python local/validate_manifest.py --manifest $output_path
    fi
fi

if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
    log "Stage 5: Compute fbank for ${subset}_dev and ${subset}_test"
    python local/compute_fbank_reazonspeech.py -s $subset -m $manifests_dir -f $fbank_dir
    python local/validate_manifest.py --manifest ${fbank_dir}/reazonspeech_${subset}_cuts_train.jsonl.gz
    python local/validate_manifest.py --manifest ${fbank_dir}/reazonspeech_${subset}_cuts_dev.jsonl.gz
    python local/validate_manifest.py --manifest ${fbank_dir}/reazonspeech_${subset}_cuts_test.jsonl.gz
fi

if [ $stage -le 6 ] && [ $stop_stage -ge 6 ]; then
    log "Stage 6: Show manifest statistics"
    python local/display_manifest_statistics.py --manifest-dir data/manifests > data/manifests/manifest_statistics.txt
    cat data/manifests/manifest_statistics.txt
fi

if [ $stage -le 7 ] && [ $stop_stage -ge 7 ]; then
    log "Stage 7: Train katakana bpe for ReazonSpeech"
    $lang_dir_k=${lang_dir}_katakana
    if [ ! -f $lang_dir_k/bpe.model ]; then
        ./local/train_bpe_model.py \
            --lang-dir $lang_dir_k \
            --vocab-size $vocab_size \
            --transcript $lang_dir_k/transcript_words.txt
    fi
fi

if [ $stage -le 8 ] && [ $stop_stage -ge 8 ]; then
    log "Stage 8: Train hiragana bpe for ReazonSpeech"
    $lang_dir_h=${lang_dir}_hiragana
    if [ ! -f $lang_dir_h/bpe.model ]; then
        ./local/train_bpe_model.py \
            --lang-dir $lang_dir_h \
            --vocab-size $vocab_size \
            --transcript $lang_dir_h/transcript_words.txt
    fi
fi