#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

nj=32
stage=1
stop_stage=1
vocab_size=500
dl_dir="/home/shahn/Datasets/aihub/002.라이브 스트리밍 영상 중국어 통번역 데이터/3.개방데이터/1.데이터"
manifests_dir=data/manifests
fbank_dir=/home/shahn/Documents/icefall/egs/librispeech/ASR/data/fbank
lang_dir=data/lang_bpe_${vocab_size}
export CUDA_VISIBLE_DEVICES=0

# Split a subset into multiple splits to avoid OOM during feature extraction.
# Each split will contain `num_per_split` utterances.
num_per_split=10000

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
    # This function is from espnet
    local fname=${BASH_SOURCE[1]##*/}
    echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh"

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
    log "Stage 1: Prepare manifest"
    mkdir -p data/manifests
    python local/prepare_manifest.py -s $subset -m $manifests_dir -r $dl_dir -l $lang_dir
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
    log "Stage 2: Compute ReazonSpeech fbank"
    python local/compute_fbank_reazonspeech.py -n $nj -s $subset -m $manifests_dir -f $fbank_dir
    if [ ! -e data/manifests/.reazonspeech-${subset}-validated.done ]; then
        python local/validate_manifest.py --manifest ${fbank_dir}/reazonspeech_${subset}_cuts_train.jsonl.gz
        python local/validate_manifest.py --manifest ${fbank_dir}/reazonspeech_${subset}_cuts_dev.jsonl.gz
        python local/validate_manifest.py --manifest ${fbank_dir}/reazonspeech_${subset}_cuts_test.jsonl.gz
        touch data/manifests/.reazonspeech-${subset}-validated.done
    fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
    log "Stage 3: Train katakana bpe for ReazonSpeech"
    $lang_dir_k=${lang_dir}_katakana
    if [ ! -f $lang_dir_k/bpe.model ]; then
        ./local/train_bpe_model.py \
            --lang-dir $lang_dir_k \
            --vocab-size $vocab_size \
            --transcript $lang_dir_k/transcript_words.txt
    fi
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
    log "Stage 4: Train hiragana bpe for ReazonSpeech"
    $lang_dir_h=${lang_dir}_hiragana
    if [ ! -f $lang_dir_h/bpe.model ]; then
        ./local/train_bpe_model.py \
            --lang-dir $lang_dir_h \
            --vocab-size $vocab_size \
            --transcript $lang_dir_h/transcript_words.txt
    fi
fi

if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
    log "Stage 5: Show manifest statistics"
    python local/display_manifest_statistics.py --manifest-dir data/manifests > data/manifests/manifest_statistics.txt
    cat data/manifests/manifest_statistics.txt
fi